const express = require('express');
const app = express();
const port = 8000;

const productsData = [
  {
    id: 1,
    name: 'iPhone 16 Pro Max 256GB | Chính hãng VN/A',
    category: 'dienthoai',
    image: './img/1.webp',
    price_new: '30.090.000đ',
    price_old: '34.990.000đ',
    tags: ['6.9 inches', '256 GB'],
    badge_left: 'Giảm 14%',
    badge_right: 'Trả góp 0%',
    member_discount: 'Smember giảm đến 301.000đ',
    desc: 'Không phí chuyển đổi khi trả góp 0% qua thẻ tín dụng kỳ hạn 3-6...',
    rating: '4.9',
  },
  {
    id: 2,
    name: 'iPhone 15 128GB | Chính hãng VN/A',
    category: 'dienthoai',
    image: './img/2.webp',
    price_new: '15.190.000đ',
    price_old: '17.290.000đ',
    tags: ['6.1 inches', '128 GB'],
    badge_left: 'Giảm 12%',
    badge_right: 'Trả góp 0%',
    member_discount: 'Smember giảm đến 150.000đ',
    desc: 'Thiết kế hiện đại, chip A16 Bionic mạnh mẽ.',
    rating: '4.8',
  },
  {
    id: 3,
    name: 'iPhone 17 Pro Max 256GB | Chính hãng',
    category: 'dienthoai',
    image: './img/3.webp',
    price_new: '37.990.000đ',
    price_old: '40.990.000đ',
    tags: ['7.0 inches', '256 GB'],
    badge_left: 'Mới',
    badge_right: 'Trả góp 0%',
    member_discount: 'Smember giảm đến 350.000đ',
    desc: 'Flagship mới nhất với công nghệ camera đột phá.',
    rating: '4.9',
  },
  {
    id: 4,
    name: 'iPhone 17 256GB | Chính hãng',
    category: 'dienthoai',
    image: './img/4.webp',
    price_new: '24.990.000đ',
    price_old: '27.890.000đ',
    tags: ['6.7 inches', '256 GB'],
    badge_left: 'Giảm 10%',
    badge_right: 'Trả góp 0%',
    member_discount: 'Smember giảm đến 250.000đ',
    desc: 'Màn hình Super Retina XDR sắc nét, hiệu năng vượt trội.',
    rating: '4.7',
  },
  {
    id: 5,
    name: 'iPhone 16 128GB | Chính hãng VN/A',
    category: 'dienthoai',
    image: './img/5.webp',
    price_new: '18.790.000đ',
    price_old: '20.490.000đ',
    tags: ['6.1 inches', '128 GB'],
    badge_left: 'Giảm 8%',
    badge_right: 'Trả góp 0%',
    member_discount: 'Smember giảm đến 180.000đ',
    desc: 'Mẫu điện thoại quốc dân, thiết kế trẻ trung.',
    rating: '4.6',
  },
  {
    id: 6,
    name: 'iPhone 15 Pro Max 256GB | Chính hãng VN/A',
    category: 'dienthoai',
    image: './img/6.webp',
    price_new: '26.990.000đ',
    price_old: '30.990.000đ',
    tags: ['6.7 inches', '256 GB'],
    badge_left: 'Giảm 13%',
    badge_right: 'Trả góp 0%',
    member_discount: 'Smember giảm đến 300.000đ',
    desc: 'Camera Tele 5X siêu nét, hiệu năng cực mạnh.',
    rating: '4.9',
  },
  {
    id: 7,
    name: 'iPhone 16 Pro 128GB | Chính hãng VN/A',
    category: 'dienthoai',
    image: './img/7.webp',
    price_new: '24.890.000đ',
    price_old: '26.790.000đ',
    tags: ['6.7 inches', '128 GB'],
    badge_left: 'Giảm 7%',
    badge_right: 'Trả góp 0%',
    member_discount: 'Smember giảm đến 200.000đ',
    desc: 'Thiết kế titan sang trọng, hiệu năng mượt mà.',
    rating: '4.8',
  },
  {
    id: 8,
    name: 'iPhone 15 Plus 128GB | Chính hãng VN/A',
    category: 'dienthoai',
    image: './img/8.webp',
    price_new: '18.790.000đ',
    price_old: '20.690.000đ',
    tags: ['6.7 inches', '128 GB'],
    badge_left: 'Giảm 9%',
    badge_right: 'Trả góp 0%',
    member_discount: 'Smember giảm đến 190.000đ',
    desc: 'Màn hình lớn, pin trâu, giá dễ tiếp cận.',
    rating: '4.7',
  },
  {
    id: 9,
    name: 'iPhone 14 Pro Max 128GB | Chính hãng VN/A',
    category: 'dienthoai',
    image: './img/9.webp',
    price_new: '25.590.000đ',
    price_old: '28.590.000đ',
    tags: ['6.7 inches', '128 GB'],
    badge_left: 'Giảm 11%',
    badge_right: 'Trả góp 0%',
    member_discount: 'Smember giảm đến 250.000đ',
    desc: 'Dynamic Island thời thượng, camera chất lượng.',
    rating: '4.8',
  },
  {
    id: 10,
    name: 'iPhone Air 256GB | Chính hãng',
    category: 'dienthoai',
    image: './img/10.webp',
    price_new: '31.990.000đ',
    price_old: '34.490.000đ',
    tags: ['6.9 inches', '256 GB'],
    badge_left: 'Hot',
    badge_right: 'Trả góp 0%',
    member_discount: 'Smember giảm đến 310.000đ',
    desc: 'Phiên bản giới hạn, thiết kế siêu mỏng nhẹ.',
    rating: '5.0',
  },
  {
    id: 11,
    name: 'MacBook Air M3 13 inch 2024 | 8GB/256GB',
    category: 'laptop',
    image: './img/macbook-air-m3.webp',
    price_new: '27.490.000đ',
    price_old: '29.990.000đ',
    tags: ['13 inch', '8GB RAM', '256GB SSD'],
    badge_left: 'Giảm 8%',
    badge_right: 'Mới 2024',
    member_discount: 'Smember giảm thêm 300.000đ',
    desc: 'Chip Apple M3 cực mạnh, thiết kế mỏng nhẹ, pin cả ngày.',
    rating: '5.0',
  },
  {
    id: 12,
    name: 'Tai nghe Apple AirPods 3 | Sạc Lightning',
    category: 'amthanh',
    image: './img/airpods-3.webp',
    price_new: '4.290.000đ',
    price_old: '4.990.000đ',
    tags: ['Audio Spatial', 'Lightning'],
    badge_left: 'Giảm 14%',
    badge_right: 'Chính hãng',
    member_discount: 'Smember giảm thêm 50.000đ',
    desc: 'Âm thanh không gian, thiết kế mới, thời lượng pin cao.',
    rating: '4.9',
  },
];

app.use((req, res, next) => {
    res.header('Access-Control-Allow-Origin', '*');
    next();
});

app.get('/', (req, res) => {
    res.json(productsData);
});

app.listen(port, () => {
    console.log(`Server Express đang chạy tại http://localhost:${port}`);
});